name: Backend CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'      # если у тебя Java 17 — поставь '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run tests
        run: mvn -B test
